server:
  port: 8000
  servlet:
    context-path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:uat}
  jackson:
    date-format: yyyy-MM-dd
    datetime-format: yyyy-MM-ddTHH:mm:ss
    time-zone: UTC
  messages:
    basename: messages
  web:
    locale: pt_BR
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximumPoolSize: 2
      connectionTimeout: 20000
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

origin-allowed: '*'

keycloak:
  enabled: true
  auth-server-url: ${keycloakUrl}
  realm: ${keycloakRealm}
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: false